args:
  latent_channels: 16
  mode: inference
  load: "/nas/shared/Gveval2/jiyatai/cpfs/CV_codes/CogVideoX-5b-sat/transformer" # This is for Full model without lora adapter
  # load: "{your lora folder} such as zRzRzRzRzRzRzR/lora-disney-08-20-13-28" # This is for Full model without lora adapter

  batch_size: 1
  input_type: txt
  sampling_num_frames: 9  # Must be 13, 11 or 9
  sampling_fps: 8
  # fp16: True # For CogVideoX-2B
  bf16: True # For CogVideoX-5B
  force_inference: True